# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82bee00d958dae4718b4ba2121234be1b2bec5d5061f460f182504a5fe0a4d41d0aa34fabd14a378676331c979957f2d0ffd6c5b0fd538e1c4f021d6fe94a0c1

test:
  secret_key_base: 648ed594a62fa71895f56d98bfa0ff4296182f1f119d59f6d7bd294eabc232e5351ba8300b7f7ef3c2d6ad88b2eb502485ca09bf1a17776c592c0c10319f7314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
